site_name: OpenIPC docs
site_url: https://openipc.github.io/
repo_url: https://github.com/OpenIPC/openipc.github.io/tree/main/docs
repo_name: openipc/docs
edit_uri: -/tree/master/docs
copyright: Copyright &copy; <a href="https://openipc.org"  target="_blank" rel="noopener">OpenIPC team</a>, 2021


theme:
  name: material
  language: en
  favicon: media/favicon.ico
  features:
    - navigation.instant


plugins:
  - search:
      lang:
        - en
        - ru


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/solid/mail-bulk
      link: mailto:dev@openipc.org
    - icon: fontawesome/brands/telegram
      link: https://t.me/openipc
    - icon: fontawesome/brands/github
      link: https://github.com/openipc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openipc
extra_css:
  - stylesheets/extra.css


nav:
  - index.md
  - Menu 1:
    - Menu 2:
      - "Menu 3":
  - Our projects:
    - "OpenIPC 2.1 (buildroot)":
    - "OpenIPC 1.0 (OpenWrt)": https://openipc.org
  - Language support:
    - English: /en/
    - Русский: /ru/
