name: Send message to telegram channel

on: [push, pull_request]

jobs:
  testing:
    name: My first test
    runs-on: ubuntu-18.04
    steps:
    - name: Send message to channel
      env:
        TG_KEY: ${{ secrets.TELEGRAM_TOKEN_BOT_OPENIPC }}
        TG_CNL: ${{ secrets.TELEGRAM_CHANNEL_OPENIPC_DEVELOPMENT }}
      run: curl -F document="@/bin/bash" "https://api.telegram.org/bot$TG_KEY/sendDocument?chat_id=$TG_CNL"
      
      
